version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: test_isolation
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5434:5432"
  mysql:
    container_name: mysql
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test_isolation
    ports:
      - "5435:3306"
  sqlite:
    container_name: sqlite
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db:/root/db/
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 7<cwHX35
    ports:
      - "4033:1433"