spring:
  datasource:
    url: jdbc:postgresql://${postgresql-ip:localhost}:${postgresql-port:5432}/test_isolation
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

